version: "3"

volumes:
  db: {}

services:
  laravel-echo-server:
    image: attractgrouphub/laravel-echo-server:1.0.0
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: http://example.com
      LARAVEL_ECHO_SERVER_DEBUG:     'true'
      LARAVEL_ECHO_SERVER_DATABASE:  sqlite
    ports:
      - 7070:7070
    restart: unless-stopped
    volumes:
      - dt:/database
